### ISSUE TITLE
iGPU video output?

### ISSUE THREAD

**Issue by 23doors** [ArsnealX/Bootloader-Backup#1]
Hey, Sorry for contacting you this way but this was the only way I found.

In your setup, do you have iGPU hdmi/displayport output working (assuming you first enable multi monitor for igpu in bios and increase dvmt)? I plan to buy MSI z370m mortar and this is pretty important for me. I would hugely appreciate you checking this out.

**Comment by ArsnealX** [comment]
Hey @23doors !
I have tested it. iGPU works fine with HDMI, but DisplayPort need some fixes to work (I got "no input" after macOS having some graphic related boot process).

**Comment by 23doors** [comment]
@ArsnealX Thanks a lot!
